In [3]:
import pandas as pd
import numpy as np

In [5]:
df_2023 = pd.read_csv(r'C:\Users\João Varella\OneDrive\Área de Trabalho\Projeto_Banco_de_Dados_João_VArella\Projeto_Tecnicas_de_Programacao_I\data\World Happiness Report 2023.csv')
df_2023.head(5)

,Country name,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,Finland,7.804,0.036,7.875,7.733,10.792,0.969,71.150,0.961,-0.019,0.182,1.778,1.888,1.585,0.535,0.772,0.126,0.535,2.363
1,Denmark,7.586,0.041,7.667,7.506,10.962,0.954,71.250,0.934,0.134,0.196,1.778,1.949,1.548,0.537,0.734,0.208,0.525,2.084
2,Iceland,7.530,0.049,7.625,7.434,10.896,0.983,72.050,0.936,0.211,0.668,1.778,1.926,1.620,0.559,0.738,0.250,0.187,2.250
3,Israel,7.473,0.032,7.535,7.411,10.639,0.943,72.697,0.809,-0.023,0.708,1.778,1.833,1.521,0.577,0.569,0.124,0.158,2.691
4,Netherlands,7.403,0.029,7.460,7.346,10.942,0.930,71.550,0.887,0.213,0.379,1.778,1.942,1.488,0.545,0.672,0.251,0.394,2.110

In [6]:
df_2023.rename(columns={'Country name':'Country',
                        'Ladder score':'Score',
                        'Explained by: Log GDP per capita':'GDP per capita',
                        'Explained by: Perceptions of corruption':'Perceptions of corruption',
                        'Explained by: Generosity':'Generosity',
                        'Explained by: Freedom to make life choices':'Freedom to make life choices'
                        })

,Country,Score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Dystopia + residual
0,Finland,7.804,0.036,7.875,7.733,10.792,0.969,71.150,0.961,-0.019,0.182,1.778,1.888,1.585,0.535,0.772,0.126,0.535,2.363
1,Denmark,7.586,0.041,7.667,7.506,10.962,0.954,71.250,0.934,0.134,0.196,1.778,1.949,1.548,0.537,0.734,0.208,0.525,2.084
2,Iceland,7.530,0.049,7.625,7.434,10.896,0.983,72.050,0.936,0.211,0.668,1.778,1.926,1.620,0.559,0.738,0.250,0.187,2.250
3,Israel,7.473,0.032,7.535,7.411,10.639,0.943,72.697,0.809,-0.023,0.708,1.778,1.833,1.521,0.577,0.569,0.124,0.158,2.691
4,Netherlands,7.403,0.029,7.460,7.346,10.942,0.930,71.550,0.887,0.213,0.379,1.778,1.942,1.488,0.545,0.672,0.251,0.394,2.110
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132,Congo (Kinshasa),3.207,0.095,3.394,3.020,7.007,0.652,55.375,0.664,0.086,0.834,1.778,0.531,0.784,0.105,0.375,0.183,0.068,1.162
133,Zimbabwe,3.204,0.061,3.323,3.084,7.641,0.690,54.050,0.654,-0.046,0.766,1.778,0.758,0.881,0.069,0.363,0.112,0.117,0.905
134,Sierra Leone,3.138,0.082,3.299,2.976,7.394,0.555,54.900,0.660,0.105,0.858,1.778,0.670,0.540,0.092,0.371,0.193,0.051,1.221
135,Lebanon,2.392,0.044,2.479,2.305,9.478,0.530,66.149,0.474,-0.141,0.891,1.778,1.417,0.476,0.398,0.123,0.061,0.027,-0.110
136,Afghanistan,1.859,0.033,1.923,1.795,7.324,0.341,54.712,0.382,-0.081,0.847,1.778,0.645,0.000,0.087,0.000,0.093,0.059,0.976

In [7]:
df_2022 = pd.read_csv(r'C:\Users\João Varella\OneDrive\Área de Trabalho\Projeto_Banco_de_Dados_João_VArella\Projeto_Tecnicas_de_Programacao_I\data\World Happiness Report 2022.csv')
df_2022.head(5)

,RANK,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.83) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,1,Finland,7.821,7.886,7.756,2.518,1.892,1.258,0.775,0.736,0.109,0.534
1,2,Denmark,7.636,7.710,7.563,2.226,1.953,1.243,0.777,0.719,0.188,0.532
2,3,Iceland,7.557,7.651,7.464,2.320,1.936,1.320,0.803,0.718,0.270,0.191
3,4,Switzerland,7.512,7.586,7.437,2.153,2.026,1.226,0.822,0.677,0.147,0.461
4,5,Netherlands,7.415,7.471,7.359,2.137,1.945,1.206,0.787,0.651,0.271,0.419

In [8]:
df_2022 = pd.read_csv(r'C:\Users\João Varella\OneDrive\Área de Trabalho\Projeto_Banco_de_Dados_João_VArella\Projeto_Tecnicas_de_Programacao_I\data\World Happiness Report 2023.csv')
df_2022.head(5)

,Country name,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,Finland,7.804,0.036,7.875,7.733,10.792,0.969,71.150,0.961,-0.019,0.182,1.778,1.888,1.585,0.535,0.772,0.126,0.535,2.363
1,Denmark,7.586,0.041,7.667,7.506,10.962,0.954,71.250,0.934,0.134,0.196,1.778,1.949,1.548,0.537,0.734,0.208,0.525,2.084
2,Iceland,7.530,0.049,7.625,7.434,10.896,0.983,72.050,0.936,0.211,0.668,1.778,1.926,1.620,0.559,0.738,0.250,0.187,2.250
3,Israel,7.473,0.032,7.535,7.411,10.639,0.943,72.697,0.809,-0.023,0.708,1.778,1.833,1.521,0.577,0.569,0.124,0.158,2.691
4,Netherlands,7.403,0.029,7.460,7.346,10.942,0.930,71.550,0.887,0.213,0.379,1.778,1.942,1.488,0.545,0.672,0.251,0.394,2.110

In [11]:
df_2022['Year'] = 2022

In [18]:
df_2022 = df_2022[['Country name','Ladder score','Explained by: Log GDP per capita','Explained by: Social support','Explained by: Healthy life expectancy','Explained by: Freedom to make life choices','Explained by: Generosity','Explained by: Perceptions of corruption','Year']]
df_2022.head(5)

,Country name,Ladder score,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Year
0,Finland,7.804,1.888,1.585,0.535,0.772,0.126,0.535,2022
1,Denmark,7.586,1.949,1.548,0.537,0.734,0.208,0.525,2022
2,Iceland,7.530,1.926,1.620,0.559,0.738,0.250,0.187,2022
3,Israel,7.473,1.833,1.521,0.577,0.569,0.124,0.158,2022
4,Netherlands,7.403,1.942,1.488,0.545,0.672,0.251,0.394,2022

In [13]:
df_2023['Year'] = 2023

In [17]:
df_2023 = df_2023[['Country name','Ladder score','Explained by: Log GDP per capita','Explained by: Social support','Explained by: Healthy life expectancy','Explained by: Freedom to make life choices','Explained by: Generosity','Explained by: Perceptions of corruption','Year']]
df_2023

,Country name,Ladder score,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Year
0,Finland,7.804,1.888,1.585,0.535,0.772,0.126,0.535,2023
1,Denmark,7.586,1.949,1.548,0.537,0.734,0.208,0.525,2023
2,Iceland,7.530,1.926,1.620,0.559,0.738,0.250,0.187,2023
3,Israel,7.473,1.833,1.521,0.577,0.569,0.124,0.158,2023
4,Netherlands,7.403,1.942,1.488,0.545,0.672,0.251,0.394,2023
...,...,...,...,...,...,...,...,...,...
132,Congo (Kinshasa),3.207,0.531,0.784,0.105,0.375,0.183,0.068,2023
133,Zimbabwe,3.204,0.758,0.881,0.069,0.363,0.112,0.117,2023
134,Sierra Leone,3.138,0.670,0.540,0.092,0.371,0.193,0.051,2023
135,Lebanon,2.392,1.417,0.476,0.398,0.123,0.061,0.027,2023
136,Afghanistan,1.859,0.645,0.000,0.087,0.000,0.093,0.059,2023